%{

#include <iostream>
#include <cstdio>
#include <cstdlib>
#include <string>

using namespace std;

extern int yylex();

void yyerror(string s){
	cerr<<"Sintaksna greska: "<<s<<endl;
	exit(EXIT_FAILURE);
}

%}


%token


%start program

%%

program: program naredba ';' {}
	| naredba ';' {}
	;
	
%%

int main(){
	if(yyparse()==0)
		cout<<"Sve ok"<<endl;
	else
		cout<<"Sintaksna greska"<<endl;
		
	exit(EXIT_SUCCESS);
}
